workflow_id: transformation
dag_config: workflows/transformation.yml
description: Brewery DQ/gold + orders KPIs
process: transformation

tasks:
  brewery_dq_gold:
    orchestrator: orchestrator.transformation:run_brewery_dq_gold
    domain_module: transformation.brewery:run_dq_gold
  kpi:
    orchestrator: orchestrator.transformation:run_kpi
    domain_module: transformation.kpi:run_kpi_pipeline
