# Host-side OIDC setup (uses local `az login`). Docker alternative: docker/azure/setup-oidc.ps1
param(
    [string]$AppName = "sp-data-platform-github",
    [string]$GitHubRepo = "VictorCappelletto/data-platform",
    [string[]]$GitHubBranches = @("main", "publish-main"),
    [string]$EnvFile = ".env",
    [string]$OutputFile = "config/azure/oidc.generated.env"
)

$ErrorActionPreference = "Stop"

function Get-EnvValue {
    param([string]$Name, [string]$Path)
    if (-not (Test-Path $Path)) { return $null }
    foreach ($line in Get-Content $Path) {
        if ($line -match "^\s*$Name=(.*)$") { return $Matches[1].Trim() }
    }
    return $null
}

az account show -o none 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) { throw "Run: az login" }

$subId = Get-EnvValue "AZURE_SUBSCRIPTION_ID" $EnvFile
if (-not $subId) { $subId = az account show --query id -o tsv }

$tenantId = Get-EnvValue "AZURE_TENANT_ID" $EnvFile
if (-not $tenantId) { $tenantId = az account show --query tenantId -o tsv }

$rg = Get-EnvValue "AZURE_RESOURCE_GROUP" $EnvFile
if (-not $rg) { $rg = "rg-olist-dev" }

$location = Get-EnvValue "AZURE_LOCATION" $EnvFile
if (-not $location) { $location = "eastus" }

$scope = "/subscriptions/$subId/resourceGroups/$rg"

Write-Host "Subscription: $subId"
Write-Host "Resource group: $rg"
Write-Host "GitHub branches: $($GitHubBranches -join ', ')"
Write-Host ""

$appId = az ad app list --display-name $AppName --query "[0].appId" -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($appId)) {
    $appId = az ad app create --display-name $AppName --query appId -o tsv
    Write-Host "Created app registration: $AppName"
} else {
    Write-Host "App registration exists: $AppName"
}

$sp = az ad sp list --filter "appId eq '$appId'" --query "[0].id" -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($sp)) {
    az ad sp create --id $appId | Out-Null
    Write-Host "Created service principal"
} else {
    Write-Host "Service principal exists"
}

$fcNamePrefix = "github-data-platform"
foreach ($branch in $GitHubBranches) {
    $subject = "repo:${GitHubRepo}:ref:refs/heads/$branch"
    $fcName = "$fcNamePrefix-$($branch -replace '[^a-zA-Z0-9-]','-')"
    Write-Host "Federated credential: $subject"

    $existingFc = az ad app federated-credential list --id $appId --query "[?subject=='$subject'].name" -o tsv 2>$null
    if ([string]::IsNullOrWhiteSpace($existingFc)) {
        $fcPath = Join-Path $env:TEMP "github-oidc-$fcName.json"
        @"
{
  "name": "$fcName",
  "issuer": "https://token.actions.githubusercontent.com",
  "subject": "$subject",
  "description": "GitHub Actions OIDC — $branch",
  "audiences": ["api://AzureADTokenExchange"]
}
"@ | Set-Content -Path $fcPath -Encoding utf8
        az ad app federated-credential create --id $appId --parameters "@$fcPath" | Out-Null
        Remove-Item $fcPath -Force -ErrorAction SilentlyContinue
        Write-Host "  created: $fcName"
    } else {
        Write-Host "  exists: $existingFc"
    }
}

$primaryBranch = $GitHubBranches[0]
$primarySubject = "repo:${GitHubRepo}:ref:refs/heads/$primaryBranch"

$assignment = az role assignment list --assignee $appId --scope $scope --role Contributor --query "[0].id" -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($assignment)) {
    az role assignment create --assignee $appId --role Contributor --scope $scope | Out-Null
    Write-Host "Assigned Contributor on $rg"
} else {
    Write-Host "RBAC Contributor already assigned on $rg"
}

$outDir = Split-Path $OutputFile -Parent
if ($outDir -and -not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir -Force | Out-Null }

@"
# Generated by docker/azure/setup-oidc.ps1
AZURE_CLIENT_ID=$appId
AZURE_TENANT_ID=$tenantId
AZURE_SUBSCRIPTION_ID=$subId
AZURE_RESOURCE_GROUP=$rg
AZURE_LOCATION=$location
GITHUB_REPO=$GitHubRepo
GITHUB_OIDC_SUBJECT=$primarySubject
GITHUB_OIDC_BRANCHES=$($GitHubBranches -join ',')
"@ | Set-Content -Path $OutputFile -Encoding utf8

Write-Host ""
Write-Host "Wrote $OutputFile"
Write-Host ""
Write-Host "GitHub Actions secrets:"
Write-Host "  AZURE_CLIENT_ID=$appId"
Write-Host "  AZURE_TENANT_ID=$tenantId"
Write-Host "  AZURE_SUBSCRIPTION_ID=$subId"
