#!/usr/bin/env bash
# Phase 2 — GitHub Actions OIDC (App Registration + federated credential + RBAC).
set -euo pipefail

APP_NAME="${AZURE_OIDC_APP_NAME:-sp-data-platform-github}"
GITHUB_REPO="${GITHUB_REPO:-VictorCappelletto/data-platform}"
GITHUB_BRANCH="${GITHUB_BRANCH:-main}"
FC_NAME="${AZURE_OIDC_FC_NAME:-github-data-platform-main}"
OUTPUT_FILE="${OIDC_OUTPUT_FILE:-config/azure/oidc.generated.env}"

load_env() {
  local env_file="${1:-.env}"
  [[ -f "${env_file}" ]] || return 0
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%$'\r'}"
    [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
    local key="${line%%=*}"
    local value="${line#*=}"
    export "${key}=${value}"
  done < "${env_file}"
}

usage() {
  cat <<EOF
Usage: setup-oidc <command>

Commands:
  setup     Create/update App Registration, SP, federated credential, RBAC
  show      Print OIDC values for GitHub secrets
  help      Show this message

Requires: az login (mount ~/.azure into container)
EOF
}

require_az() {
  az account show >/dev/null 2>&1 || {
    echo "Not logged in. Run on host: az login" >&2
    exit 1
  }
}

get_app_id() {
  az ad app list --display-name "${APP_NAME}" --query "[0].appId" -o tsv 2>/dev/null | tr -d '[:space:]'
}

cmd_setup() {
  require_az
  load_env ".env"

  local sub_id tenant_id rg scope
  sub_id="${AZURE_SUBSCRIPTION_ID:-$(az account show --query id -o tsv)}"
  tenant_id="${AZURE_TENANT_ID:-$(az account show --query tenantId -o tsv)}"
  rg="${AZURE_RESOURCE_GROUP:-rg-olist-dev}"
  scope="/subscriptions/${sub_id}/resourceGroups/${rg}"

  echo "Subscription: ${sub_id}"
  echo "Tenant:       ${tenant_id}"
  echo "Scope:        ${scope}"
  echo "GitHub repo:  ${GITHUB_REPO} (branch ${GITHUB_BRANCH})"
  echo ""

  local app_id
  app_id="$(get_app_id)"
  if [[ -z "${app_id}" ]]; then
    app_id="$(az ad app create --display-name "${APP_NAME}" --query appId -o tsv)"
    echo "Created app registration: ${APP_NAME} (${app_id})"
  else
    echo "App registration exists: ${APP_NAME} (${app_id})"
  fi

  local sp_id
  sp_id="$(az ad sp list --filter "appId eq '${app_id}'" --query "[0].id" -o tsv 2>/dev/null | tr -d '[:space:]')"
  if [[ -z "${sp_id}" ]]; then
    az ad sp create --id "${app_id}" >/dev/null
    echo "Created service principal"
  else
    echo "Service principal exists"
  fi

  local subject="repo:${GITHUB_REPO}:ref:refs/heads/${GITHUB_BRANCH}"
  local fc_path
  fc_path="$(mktemp)"
  jq -n \
    --arg name "${FC_NAME}" \
    --arg subject "${subject}" \
    '{
      name: $name,
      issuer: "https://token.actions.githubusercontent.com",
      subject: $subject,
      description: "GitHub Actions OIDC",
      audiences: ["api://AzureADTokenExchange"]
    }' > "${fc_path}"

  local existing_fc
  existing_fc="$(az ad app federated-credential list --id "${app_id}" --query "[?subject=='${subject}'].name" -o tsv 2>/dev/null || true)"
  if [[ -n "${existing_fc}" ]]; then
    echo "Federated credential exists: ${existing_fc}"
  else
    az ad app federated-credential create --id "${app_id}" --parameters "@${fc_path}" >/dev/null
    echo "Created federated credential: ${FC_NAME}"
  fi
  rm -f "${fc_path}"

  local assignment
  assignment="$(az role assignment list \
    --assignee "${app_id}" \
    --scope "${scope}" \
    --role Contributor \
    --query "[0].id" -o tsv 2>/dev/null || true)"
  if [[ -n "${assignment}" ]]; then
    echo "RBAC Contributor already assigned on ${rg}"
  else
    az role assignment create \
      --assignee "${app_id}" \
      --role Contributor \
      --scope "${scope}" >/dev/null
    echo "Assigned Contributor on ${rg}"
  fi

  mkdir -p "$(dirname "${OUTPUT_FILE}")"
  cat > "${OUTPUT_FILE}" <<EOF
# Generated by docker/azure setup-oidc — safe to use for GitHub Actions secrets (not a password)
AZURE_CLIENT_ID=${app_id}
AZURE_TENANT_ID=${tenant_id}
AZURE_SUBSCRIPTION_ID=${sub_id}
AZURE_RESOURCE_GROUP=${rg}
AZURE_LOCATION=${AZURE_LOCATION:-eastus}
GITHUB_REPO=${GITHUB_REPO}
GITHUB_OIDC_SUBJECT=${subject}
EOF
  echo ""
  echo "Wrote ${OUTPUT_FILE}"
  echo ""
  echo "GitHub Actions secrets to set:"
  echo "  AZURE_CLIENT_ID=${app_id}"
  echo "  AZURE_TENANT_ID=${tenant_id}"
  echo "  AZURE_SUBSCRIPTION_ID=${sub_id}"
}

cmd_show() {
  load_env "${OUTPUT_FILE}"
  if [[ ! -f "${OUTPUT_FILE}" ]]; then
    echo "Run: setup-oidc setup" >&2
    exit 1
  fi
  cat "${OUTPUT_FILE}"
}

main() {
  local cmd="${1:-help}"
  shift || true
  case "${cmd}" in
    setup) cmd_setup "$@" ;;
    show) cmd_show "$@" ;;
    help|-h|--help) usage ;;
    *)
      echo "Unknown command: ${cmd}" >&2
      usage
      exit 1
      ;;
  esac
}

main "$@"
