#!/usr/bin/env bash
# Secrets pipeline — per-variable encrypt/decrypt via SOPS + age.
# Mixed state is supported: already-encrypted keys stay untouched when adding new ones.
set -euo pipefail

SECRETS_DIR="${SECRETS_DIR:-encrypted-secrets}"
SECRETS_FILE="${SECRETS_FILE:-${SECRETS_DIR}/local.env}"
AGE_KEY_FILE="${SOPS_AGE_KEY_FILE:-${SECRETS_DIR}/.age-key}"
AGE_PUB_FILE="${SECRETS_DIR}/.age.pub"
SOPS_CONFIG="${SOPS_CONFIG:-/workspace/.sops.yaml}"
DECRYPTED_ENV="${DECRYPTED_ENV:-/workspace/.env}"

export SOPS_AGE_KEY_FILE="${AGE_KEY_FILE}"

usage() {
  cat <<'EOF'
Usage: secrets <command> [args]

Commands:
  init                  Generate age key + empty encrypted store (first-time setup)
  set KEY=VALUE         Encrypt/update a single variable (others unchanged)
  add FILE              Add variables from FILE (only lines in FILE are touched)
  decrypt [OUT]         Write decrypted env (default: .env at repo root)
  edit                  Open encrypted file in $EDITOR (SOPS)
  export                Print decrypted env to stdout
  status                Show which keys exist and whether they are encrypted
  bootstrap FILE        Add missing keys from FILE (skip existing)
  decrypt-if-ready      Decrypt when key exists; no-op otherwise
  prepare               init + bootstrap + merge .env.example → .env
  help                  Show this message

Examples:
  secrets set MSSQL_SA_PASSWORD='Olist@Dev123!'
  secrets add config/env/secrets.pending.env
  secrets decrypt
  secrets status

Workflow (A new, B and C already encrypted):
  1. echo "VAR_A=plain-value" > config/env/secrets.pending.env
  2. secrets add config/env/secrets.pending.env
  3. secrets decrypt
EOF
}

require_key() {
  if [[ ! -f "${AGE_KEY_FILE}" ]]; then
    echo "Missing age private key: ${AGE_KEY_FILE}" >&2
    echo "Run: secrets init" >&2
    exit 1
  fi
}

write_sops_config() {
  local pub_key="$1"
  cat > "${SOPS_CONFIG}" <<EOF
# Generated by docker/secrets — do not edit the public key by hand after init.
creation_rules:
  - path_regex: encrypted-secrets/.*\\.env\$
    age: ${pub_key}
EOF
}

cmd_init() {
  mkdir -p "${SECRETS_DIR}"

  if [[ ! -f "${AGE_KEY_FILE}" ]]; then
    age-keygen -o "${AGE_KEY_FILE}" >/dev/null
    echo "Created private key: ${AGE_KEY_FILE} (never commit)"
  fi

  age-keygen -y "${AGE_KEY_FILE}" > "${AGE_PUB_FILE}"
  echo "Public key: ${AGE_PUB_FILE}"

  local pub_key
  pub_key="$(tr -d '[:space:]' < "${AGE_PUB_FILE}")"
  write_sops_config "${pub_key}"

  if [[ ! -f "${SECRETS_FILE}" ]] || ! grep -q '^sops_version=' "${SECRETS_FILE}" 2>/dev/null; then
    printf '# Encrypted secrets store — add keys with: secrets set KEY=VALUE\n' > "${SECRETS_FILE}"
    sops --encrypt --in-place "${SECRETS_FILE}"
    echo "Created encrypted store: ${SECRETS_FILE}"
  else
    echo "Store already exists: ${SECRETS_FILE}"
  fi

  echo "Done. Add a variable: secrets set MY_VAR=value"
}

parse_key_value() {
  local pair="$1"
  if [[ "${pair}" != *"="* ]]; then
    echo "Expected KEY=VALUE, got: ${pair}" >&2
    exit 1
  fi
  KEY="${pair%%=*}"
  VALUE="${pair#*=}"
  if [[ -z "${KEY}" ]]; then
    echo "Empty key in: ${pair}" >&2
    exit 1
  fi
}

cmd_set() {
  require_key
  [[ $# -ge 1 ]] || { echo "Usage: secrets set KEY=VALUE" >&2; exit 1; }
  parse_key_value "$1"
  sops --set "[\"${KEY}\"] \"${VALUE}\"" "${SECRETS_FILE}"
  echo "Set ${KEY} (encrypted; other keys unchanged)"
}

cmd_add() {
  require_key
  local pending_file="$1"
  [[ -f "${pending_file}" ]] || { echo "File not found: ${pending_file}" >&2; exit 1; }

  local count=0
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%$'\r'}"
    [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
    parse_key_value "${line}"
    sops --set "[\"${KEY}\"] \"${VALUE}\"" "${SECRETS_FILE}"
    echo "  + ${KEY}"
    count=$((count + 1))
  done < "${pending_file}"

  if [[ "${count}" -eq 0 ]]; then
    echo "No variables found in ${pending_file}" >&2
    exit 1
  fi
  echo "Added ${count} variable(s). Existing encrypted keys were not re-written."
}

cmd_decrypt() {
  require_key
  local out="${1:-${DECRYPTED_ENV}}"
  sops --decrypt "${SECRETS_FILE}" > "${out}"
  echo "Decrypted → ${out}"
}

cmd_export() {
  require_key
  sops --decrypt "${SECRETS_FILE}"
}

cmd_edit() {
  require_key
  sops "${SECRETS_FILE}"
}

cmd_bootstrap() {
  require_key
  local bootstrap_file="${1:-config/env/secrets.bootstrap.env}"
  [[ -f "${bootstrap_file}" ]] || { echo "Bootstrap file not found: ${bootstrap_file}" >&2; exit 1; }

  local decrypted=""
  if [[ -f "${SECRETS_FILE}" ]]; then
    decrypted="$(mktemp)"
    sops --decrypt "${SECRETS_FILE}" > "${decrypted}" 2>/dev/null || true
  fi

  local added=0 skipped=0
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%$'\r'}"
    [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
    parse_key_value "${line}"
    if [[ -n "${decrypted}" ]] && grep -q "^${KEY}=" "${decrypted}" 2>/dev/null; then
      echo "  skip ${KEY} (already in store)"
      skipped=$((skipped + 1))
      continue
    fi
    sops --set "[\"${KEY}\"] \"${VALUE}\"" "${SECRETS_FILE}"
    echo "  + ${KEY}"
    added=$((added + 1))
  done < "${bootstrap_file}"

  [[ -n "${decrypted}" ]] && rm -f "${decrypted}"
  echo "Bootstrap: ${added} added, ${skipped} skipped"
}

cmd_decrypt_if_ready() {
  if [[ ! -f "${AGE_KEY_FILE}" ]] || [[ ! -f "${SECRETS_FILE}" ]]; then
    echo "Skip decrypt: secrets store not initialized (run: secrets init)"
    return 0
  fi
  cmd_decrypt "$@"
}

merge_env_file() {
  local base_file="$1"
  local secrets_file="$2"
  local out_file="$3"

  [[ -f "${base_file}" ]] || { echo "Missing base env: ${base_file}" >&2; exit 1; }
  cp "${base_file}" "${out_file}"

  [[ -f "${secrets_file}" ]] || return 0

  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%$'\r'}"
    [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
    local key="${line%%=*}"
    local value="${line#*=}"
    [[ "${key}" == sops_* ]] && continue

    local tmp="${out_file}.merge"
    grep -v "^${key}=" "${out_file}" > "${tmp}" 2>/dev/null || true
    printf '%s=%s\n' "${key}" "${value}" >> "${tmp}"
    mv "${tmp}" "${out_file}"
  done < "${secrets_file}"
}

cmd_prepare() {
  local bootstrap_file="${1:-config/env/secrets.bootstrap.env}"
  local example_file="${2:-.env.example}"
  local out="${DECRYPTED_ENV}"

  if [[ ! -f "${AGE_KEY_FILE}" ]] || [[ ! -f "${SECRETS_FILE}" ]] || ! grep -q '^sops_version=' "${SECRETS_FILE}" 2>/dev/null; then
    cmd_init
  fi

  if [[ -f "${bootstrap_file}" ]]; then
    cmd_bootstrap "${bootstrap_file}"
  fi

  local decrypted=""
  decrypted="$(mktemp)"
  sops --decrypt "${SECRETS_FILE}" > "${decrypted}"
  merge_env_file "${example_file}" "${decrypted}" "${out}"
  rm -f "${decrypted}"

  echo "Prepared ${out} (.env.example + encrypted secrets)"
}

cmd_status() {
  require_key
  [[ -f "${SECRETS_FILE}" ]] || { echo "No secrets file yet. Run: secrets init" >&2; exit 1; }

  echo "Store: ${SECRETS_FILE}"
  echo ""
  printf "%-32s %s\n" "KEY" "STATE"
  printf "%-32s %s\n" "---" "-----"

  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%$'\r'}"
    [[ -z "${line}" || "${line}" =~ ^[[:space:]]*# ]] && continue
    local key="${line%%=*}"
    local rest="${line#*=}"
    [[ "${key}" == sops_* ]] && continue
    local state="plaintext"
    if [[ "${rest}" =~ ^ENC\[ ]]; then
      state="encrypted"
    fi
    printf "%-32s %s\n" "${key}" "${state}"
  done < "${SECRETS_FILE}"
}

main() {
  local cmd="${1:-help}"
  shift || true

  case "${cmd}" in
    init) cmd_init "$@" ;;
    set) cmd_set "$@" ;;
    add) cmd_add "$@" ;;
    bootstrap) cmd_bootstrap "$@" ;;
    decrypt) cmd_decrypt "$@" ;;
    decrypt-if-ready) cmd_decrypt_if_ready "$@" ;;
    prepare) cmd_prepare "$@" ;;
    export) cmd_export "$@" ;;
    edit) cmd_edit "$@" ;;
    status) cmd_status "$@" ;;
    help|-h|--help) usage ;;
    *)
      echo "Unknown command: ${cmd}" >&2
      usage
      exit 1
      ;;
  esac
}

main "$@"
